quote/config/routes.rb
Rails.application.routes.draw do

  get "/sign_in" => 'session#new', as: :sign_in
  get "/sign_out" => 'session#destroy', as: :sign_out
  post "/auth" => 'session#create', as: :auth

  post "/follow/:id" => 'users#follow', as: :follow
  delete "/follow/:id" => 'users#delete', as: :unfollow

  root 'pages#dashboard'

end

quote/app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

quote/app/models/quotable.rb
class Quotable < ActiveRecord::Base
  belongs_to :user
end

quote/app/models/user.rb
class User < ActiveRecord::Base
  has_many :quotables
  has_secure_password
  acts_as_followable
  acts_as_follower
end

quote/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def authenticate_user!
    user_id = session[:user_id]
    @current_user = User.find_by id: user_id
    if @current_user.nil?
      redirect_to sign_in_path
    end
  end
end

quote/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action do
    authenticate_user!
  end

  def dashboard



    ids_of_my_followers = @current_user.following_users
                                       .pluck(:id)

    timeline = ids_of_my_followers << @current_user.id
    @quotables = Quotable.where(user_id: timeline).order("created_at desc")

    @users = User.all
                 .reject{|u| @current_user.following? u}
                 .reject{|u| @current_user == u}
    # exclude current_user
    # exclude anyone I'm following

  end
end

quote/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by username: username
    if (user) && (user.authenticate password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end
end

quote/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action do
    authenticate_user!
  end

  def follow
    user = User.find params[:id]
    @current_user.follow user
    redirect_to root_path, notice: "You just followed #{user.username}"
  end

  def delete
    user = User.find params[:id]
    @current_user.stop_following user
    redirect_to root_path, notice: "You unfollowed #{user.username}"
  end
end

quote/app/helpers/application_helper.rb
module ApplicationHelper
end

quote/app/helpers/pages_helper.rb
module PagesHelper
end

quote/app/helpers/session_helper.rb
module SessionHelper
end

quote/app/helpers/users_helper.rb
module UsersHelper
end

quote/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <div class="notice">
    <%= notice %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

quote/app/views/pages/dashboard.html.erb
<h1>Quotables</h1>

<p>Hi <%= @current_user.username %></p>
<hr/>

<main>
  <article>

    <h1>Timeline</h1>

    <% @quotables.each do |quote| %>
      <div class="quotable">
        <%= quote.content %>
        <p class="meta">
          <em><%= quote.user.username %> - <%= distance_of_time_in_words_to_now quote.created_at %> ago</em>
        </p>
      </div>
    <% end %>
  </article>

  <aside>

<h4>People You Follow</h4>

<ul>
  <% @current_user.following_users.each do |user| %>
    <li>
      <%= user.username %>
      <%= link_to 'Unfollow', unfollow_path(id: user.id), method: :delete %>
    </li>
  <% end %>
</ul>

<h4>Other People You might Find interesting</h4>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.username %>
      <%= link_to "Follow this user", follow_path(id: user.id), method: :post %>
    </li>
  <% end %>
</ul>
</aside>
</main>

quote/app/views/session/new.html.erb
<h1>Sign in!</h1>

<%= form_tag auth_path, method: :post do %>
  <div>
    <%= label_tag :username %><br/>
    <%= text_field_tag :username %>
  </div>
  <div>
    <%= label_tag :password %><br/>
    <%= password_field_tag :password %>
  </div>
  <div>
    <%= submit_tag "Sign In" %>
  </div>

<% end %>